@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AttractionList *-right-> "1" UniqueAttractionList
AttractionList *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueAttractionList
UniqueTagList -[hidden]down- UniqueAttractionList

UniqueTagList *-right-> "*" Tag
UniqueAttractionList -right-> Attraction

Attraction -up-> "*" Tag

@enduml
