@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
Interface ReadOnlyAttractionList <<Interface>>
Interface ReadOnlyItineraryList <<Interface>>
Interface ReadOnlyItineraryAttractionList <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AttractionList
Class ItineraryList
Class ItineraryAttractionList
Class Model
Class ModelManager
Class UserPrefs
Interface ReadOnlyUserPrefs <<Interface>>

Package Attraction {
Class Attraction
Class UniqueAttractionList
}

Package Itinerary {
Class Itinerary
Class UniqueItineraryList
}

Package ItineraryAttraction {
Class ItineraryAttraction
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AttractionList .up.|> ReadOnlyAttractionList
ItineraryList .up.|> ReadOnlyItineraryList
ItineraryAttractionList .up.|> ReadOnlyItineraryAttractionList

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager --> "1" AttractionList
ModelManager --> "1" ItineraryList
ModelManager --> "1" ItineraryAttractionList
ModelManager --> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AttractionList *--> "1" UniqueAttractionList
UniqueAttractionList --> "*" Attraction

ItineraryList *--> "1" UniqueItineraryList
UniqueItineraryList --> "*" Itinerary

ItineraryAttractionList --> "*" ItineraryAttraction

ItineraryAttraction --|> Attraction

ModelManager --> "1" Attraction : filtered attraction list
ModelManager --> "1" Itinerary : filtered itinerary list
@enduml
