@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface AttractionListStorage <<Interface>>
Interface ItineraryListStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonAttractionListStorage
Class JsonItineraryListStorage

StorageManager .up.|> Storage
StorageManager --> UserPrefsStorage
StorageManager --> AttractionListStorage
StorageManager --> ItineraryListStorage

JsonItineraryListStorage .up.|> ItineraryListStorage
JsonItineraryListStorage .down.> JsonSerializableItineraryList
JsonSerializableItineraryList .down.> JsonAdaptedItinerary
JsonAdaptedItinerary .down.> JsonAdaptedDay
JsonAdaptedDay .down.> JsonAdaptedItineraryAttraction

JsonAttractionListStorage .up.|> AttractionListStorage
JsonAttractionListStorage .down.> JsonSerializableAttractionList
JsonSerializableAttractionList .down.> JsonAdaptedAttraction
JsonAdaptedAttraction .down.> JsonAdaptedTag

JsonUserPrefsStorage .up.|> UserPrefsStorage


@enduml
